version: '3'

volumes:
  mongo_data_local: {}

services:
  golang: &golang
    build:
      context: .
      dockerfile: ./compose/development/Dockerfile
    image: echo-app_local
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  mongodb:
    image: mongo:4.4.2
    volumes:
      - mongo_data_local:/data/db
