version: '3'

volumes:
  mongo_data_production: {}

services:
  golang: &golang
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    image: echo-app_production
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
  mongodb:
    image: mongo:4.4.2
    volumes:
      - mongo_data_production:/data/db
